### PR TITLE
Made the the config scale up by .5

### PR DESCRIPTION
**Pull request by kckarnige**
I haven't been able to test this for myself due to issues with my modding setup, so I suggest testing this for yourself before merging, _cool mod btw :D_

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
moving by 0.5 does in fact work fine. issue with this PR is that the slider was left as an integer slider so you cant have decimal inputs. already fixed this up (and a few other changes) on my side and will push a release soon

**Comment by kckarnige** [comment]
Alr, thanks for checking this out, been wanting to use this but noticed it was just barely bigger than my screen

**Comment by MicrocontrollersDev** [comment]
yeah makes sense. im also allowing to go less than 1x now in case you use gui auto and just want it smaller. and also realized for people using the smallest gui scale i need to make the max bigger 👍

**Comment by MicrocontrollersDev** [comment]
released as of 1.1.0

**Pull request closed without merging**
